general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 10

[window]
padding.x = 2
padding.y = 2
decorations = "None"

[terminal.shell]
program = "bash"
args = ["-l", "-c", "tmux attach || tmux"]

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
